### ISSUE TITLE
Palestrante incorreto confirmado em palestra 

### ISSUE THREAD

**Issue by andreybleme** [gdg-bh/devfestbh.github.io#1]
No site, a talk "Metodologias CSS" tem como palestrante Lucas Andrey. 
http://devfestbh.com.br/schedule/day1?sessionId=126 :x: 

O correto seria a palestra "Anti-patterns & premature optimization" ter as informações sobre esse palestrante.
http://devfestbh.com.br/schedule/day1?sessionId=131  :white_check_mark:.

**Comment by yanmagale** [comment]
Obrigado pelo feedback Lucas. A correção foi feita e poderá ser vista na próxima atualização do site, que saira daqui a pouquinho :D
